export const SITE_COPY = {
  ar: {
    nav: { home: "البداية", services: "الأنظمة", portfolio: "الأعمال", about: "عالم LENA", ai: "الذكاء التشغيلي", contact: "ابدأ مشروعك", dashboard: "لوحة التحكم", start: "لنتحدث" },
    common: { explore: "اكتشف عالم LENA", viewWork: "عرض الأنظمة", contact: "ابدأ مشروعك", empty: "لا توجد بيانات للعرض حاليًا.", theme: "تبديل المظهر", language: "English" },
    home: { eyebrow: "LENA DIGITAL HOUSE — OPERATING SYSTEMS", title: "نبني أنظمة تشغيل", titleAccent: "للأعمال الحقيقية", intro: "نحوّل العمل اليومي المتفرق إلى نظام واضح يربط الأشخاص والأصول والمال والعمليات في مكان واحد.", capabilities: "عوالم تشغيل مبنية لقطاعات حقيقية", capabilitiesIntro: "كل نظام يبدأ من مشكلة تشغيلية فعلية، ويحافظ على خصوصية القطاع مع الاستفادة من جذور تشغيل تتكرر بين الأعمال.", work: "LENA OPERATING WORLDS", workIntro: "منتجات تشغيلية مستقلة، مرتبطة داخل بيت رقمي واحد بدل مجموعة تطبيقات متفرقة.", ctaTitle: "هل عملك يحتاج نظام تشغيل أوضح؟", ctaText: "صف لنا كيف يعمل يومك الآن، ونحدد أين يمكن للنظام أن يقلل التشتت والعمل اليدوي." },
    services: { eyebrow: "أنظمة حسب القطاع", title: "ابدأ من طبيعة عملك، لا من قائمة خدمات تقنية", intro: "اختر القطاع الأقرب لعملك لترى المشكلة التشغيلية، من يستخدم النظام يوميًا، وما الذي يديره فعليًا." },
    portfolio: { eyebrow: "الأنظمة والمنتجات", title: "أنظمة تشغيل مبنية حول عمل يومي حقيقي", intro: "هنا نعرض المنتجات كما تعمل: المشكلة، المستخدمون، العمليات، الأدلة المتاحة، وكيف تتحول الخطوات المتفرقة إلى مسار واحد واضح.", empty: "لا توجد دراسات منتجات منشورة حاليًا." },
    about: { eyebrow: "داخل LENA", title: "بيت رقمي لأنظمة تشغيل متعددة، بعقل تشغيلي واحد", intro: "LENA Digital House يجمع أنظمة لقطاعات مختلفة داخل بنية مشتركة: كل منتج يحتفظ بمنطق عمله، بينما تكشف LENA الجذور المتكررة والعلاقات ومسار التشغيل.", approachTitle: "كيف نعمل", approach: ["نبدأ من سير العمل الحقيقي لا من شكل الواجهة", "نبني لكل قطاع نظامه بدل إجباره على قالب عام", "نستخرج الجذور المشتركة بعد إثباتها في المنتجات", "نربط الأنظمة تدريجيًا بالذاكرة والإشارات والذكاء التشغيلي"] },
    ai: {
      eyebrow: "الذكاء التشغيلي",
      title: "ذكاء يفهم السياق والحالة والخطوة التالية",
      intro: "الذكاء داخل LENA يبدأ من حقيقة النظام: المسار الحالي، الذاكرة، الإشارات وبنية العالم. لا نضيف روبوت محادثة منفصلًا عن العمل.",
      empty: "طبقة الذكاء تتطور فوق أنظمة التشغيل الحقيقية، لا بدلًا منها.",
      readsTitle: "ماذا يقرأ",
      reads: "المسار الحالي، والذاكرة المكانية، وسلطة مصدر الإشارات، وWorld Graph. لا يُستنتج غير ذلك.",
      honestyTitle: "ماذا لا يخترع",
      honesty: "لا أرقام تشغيل حية، ولا نشاط منتجات، ولا إشارات تجريبية. ما دام المصدر المصرّح به غير متصل، تبقى الطبقة صريحة حول الغياب.",
      whereTitle: "أين يعيش",
      where: "داخل عالم LENA: الكوكبة، والأطلس، وغرفة القيادة. ليس روبوت محادثة فوق الموقع.",
      worldsTitle: "العوالم التي يقرأها",
      worldsIntro: "نفس الأنظمة العلنية في World. لا كتالوج إبداعي منفصل، ولا منتجات مخفية تُعرض كأنها عامة.",
      enterWorld: "ادخل عالم LENA",
      openAtlas: "افتح الأطلس",
      openCommand: "غرفة قيادة العالم",
    },
    contact: { eyebrow: "ابدأ من عملك الحقيقي", title: "صف لنا كيف تدير العمل اليوم، ونحدد أين يبدأ النظام", intro: "أرسل المشكلة التشغيلية أو سير العمل الحالي، أو تواصل مباشرة عبر واتساب أو البريد.", call: "اتصال", whatsapp: "واتساب", email: "البريد الإلكتروني", notConfigured: "تُضبط بيانات التواصل من إعدادات النشر." },
    footer: { description: "بيت رقمي يبني أنظمة تشغيل للأعمال الحقيقية، ويجمعها تدريجيًا داخل عالم LENA وطبقة ذكاء مشتركة.", links: "روابط سريعة", contact: "ابدأ المحادثة", rights: "جميع الحقوق محفوظة." },
    dashboard: { title: "لوحة تحكم LENA", subtitle: "إدارة الاستفسارات والمحتوى", inquiries: "الاستفسارات", portfolio: "المشاريع والأعمال", content: "المحتوى", empty: "لا توجد بيانات للعرض حاليًا." },
  },
  en: {
    nav: { home: "Opening", services: "Systems", portfolio: "Work", about: "Inside LENA", ai: "Operating Intelligence", contact: "Start a Project", dashboard: "Dashboard", start: "Let's Talk" },
    common: { explore: "Enter LENA", viewWork: "View Systems", contact: "Start a Project", empty: "There is no data to display yet.", theme: "Toggle theme", language: "العربية" },
    home: { eyebrow: "LENA DIGITAL HOUSE — OPERATING SYSTEMS", title: "We build operating systems", titleAccent: "for real businesses", intro: "We turn scattered daily work into a clear operating system connecting people, assets, money, and workflows in one place.", capabilities: "Operating worlds built for real industries", capabilitiesIntro: "Each system starts from a real operational problem, keeps the industry's own logic, and reveals the operating roots that repeat across businesses.", work: "LENA OPERATING WORLDS", workIntro: "Independent operating products connected inside one digital house instead of a collection of unrelated apps.", ctaTitle: "Does your business need a clearer operating system?", ctaText: "Describe how the work runs today and we will identify where a system can reduce fragmentation and manual effort." },
    services: { eyebrow: "Systems by industry", title: "Start from how your business works, not from a list of technical services", intro: "Choose the industry closest to your work to see the operational problem, who uses the system daily, and what it actually runs." },
    portfolio: { eyebrow: "Systems and products", title: "Operating systems built around real daily work", intro: "Products are shown as they operate: the problem, users, workflows, available evidence, and how scattered steps become one clear operating flow.", empty: "No product case studies are published yet." },
    about: { eyebrow: "Inside LENA", title: "One digital house for multiple operating systems, connected by one operating intelligence", intro: "LENA Digital House connects systems for different industries through shared structure: each product keeps its domain logic while LENA reveals repeated roots, relationships, and operating paths.", approachTitle: "How we work", approach: ["Start from the real workflow, not the interface surface", "Build for each industry's logic instead of forcing a universal template", "Extract shared operating roots only after products prove them", "Connect systems gradually through memory, signals, and operating intelligence"] },
    ai: {
      eyebrow: "Operating Intelligence",
      title: "Intelligence that understands context, state, and the next useful place",
      intro: "LENA intelligence starts from product truth: current route, memory, signals, and World structure. It is not a disconnected chatbot layered on top.",
      empty: "The intelligence layer grows on top of real operating systems, never instead of them.",
      readsTitle: "What it reads",
      reads: "Current route, spatial memory, signal-source authority, and the World Graph. Nothing else is inferred.",
      honestyTitle: "What it will not invent",
      honesty: "No live operational counts, product activity, or demo signals. Until an authorized source is connected, the layer stays explicit about absence.",
      whereTitle: "Where it lives",
      where: "Inside LENA World: the constellation, Atlas, and Command. It is not a chatbot sitting on top of the site.",
      worldsTitle: "Worlds it can read",
      worldsIntro: "The same public systems World already shows. No separate creative catalog, and no hidden products presented as public.",
      enterWorld: "Enter LENA World",
      openAtlas: "Open the Atlas",
      openCommand: "World Command",
    },
    contact: { eyebrow: "Start from the real operation", title: "Show us how the work runs today, and we will identify where the system should begin", intro: "Share the operational problem or current workflow, or reach us directly by WhatsApp or email.", call: "Call", whatsapp: "WhatsApp", email: "Email", notConfigured: "Contact details are configured through deployment settings." },
    footer: { description: "A digital house building operating systems for real businesses, progressively connected through LENA World and a shared intelligence layer.", links: "Quick Links", contact: "Start the conversation", rights: "All rights reserved." },
    dashboard: { title: "LENA Dashboard", subtitle: "Manage inquiries and content", inquiries: "Inquiries", portfolio: "Projects and Work", content: "Content", empty: "There is no data to display yet." },
  },
} as const;

export type SiteLocale = keyof typeof SITE_COPY;
