import { ArrowDown, ArrowUpRight } from "lucide-react";
import { Link } from "react-router";
import LenaCta from "@/components/LenaCta";
import SeoHead from "@/components/SeoHead";
import SystemGrid from "@/components/SystemGrid";
import DigitalHouseOrbit from "@/features/home/DigitalHouseOrbit";
import ProcessSection from "@/features/home/ProcessSection";
import PublicShell from "@/layouts/PublicShell";
import { pageSeo } from "@/content/seo";
import { organizationJsonLd } from "@/lib/seo";
import { usePreferences } from "@/providers/preferences";

export default function Home() { const { locale } = usePreferences(); const seo = pageSeo("home", locale); return <PublicShell><SeoHead title={seo.title} description={seo.description} path="/" jsonLd={organizationJsonLd(locale)} /><section className="lena-hero lena-container"><div><p className="lena-kicker">LENA DIGITAL HOUSE — CREATIVE SYSTEMS & EXPERIENCES</p><h1>{locale === "ar" ? <>أنظمة تُدير <span>يوم عملك</span></> : <>Systems that run <span>your working day</span></>}</h1><p className="lena-lead">{locale === "ar" ? "نبني أنظمة تشغيل للأعمال التي تُدار اليوم على الورق ومجموعات واتساب: العقارات، المراكز الصحية، معارض التأجير، شركات الاستثمار، الضيافة، ومخازن إعادة التدوير. بناها من أدار هذا العمل قبل أن يبرمجه." : "We build operating systems for businesses still run on paper and WhatsApp groups: property, health centres, rental showrooms, investment firms, hospitality, and recycling warehouses. Built by someone who ran the work before he automated it."}</p><div className="lena-actions"><Link className="lena-primary" to="/services">{locale === "ar" ? "اكتشف عالم LENA" : "Enter LENA"}<ArrowUpRight size={16} /></Link><Link className="lena-secondary" to="/portfolio">{locale === "ar" ? "شاهد الأعمال" : "View work"}</Link></div><a className="lena-scroll" href="#solutions"><ArrowDown size={15} />{locale === "ar" ? "تمهّل… واكتشف العالم" : "Slow down… enter the world"}</a></div><DigitalHouseOrbit /></section><section className="lena-section" id="solutions"><div className="lena-container"><p className="lena-kicker">{locale === "ar" ? "الأنظمة حسب القطاع" : "Systems by industry"}</p><h2 className="lena-section-title">{locale === "ar" ? "كل نظام بدأ من مشكلة تشغيلية حقيقية، لا من فكرة على ورقة" : "Every system started from a real operational problem, not a concept on a page"}</h2><p className="lena-section-lead">{locale === "ar" ? "المنتجات تظهر هنا كجزء من عمل LENA. تصفّح أي نظام لترى ما الذي يديره." : "Products appear here as part of LENA’s work. Browse any system to see what it runs."}</p><SystemGrid /></div></section><ProcessSection /><LenaCta /></PublicShell>; }
